import {ScrollView, StyleSheet, Text, View} from 'react-native';
import {PageContainer} from '../../components/Container';

const PrivacyPolicy = ({navigation}) => {
  return (
    <PageContainer>
      <Text style={{paddingLeft: 15, height: 30, textTransform: 'uppercase'}}>
        Privacy Policy
      </Text>
      <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{paddingBottom: 50}}>
        <View style={styles.paraBox}>
          <Text style={styles.paraText}>
            LOREM IPSUM DOLOR SIT AMET, CONSECTETUER ADIPISCING ELIT, SED DIAM
            NONUMMY NIBH EUISMOD TINCIDUNT UT LAOREET DOLORE MAGNA ALIQUAM ERAT
            VOLUTPAT. UT WISI ENIM AD MINIM VENIAM, QUIS NOSTRUD EXERCI TATION
            ULLAMCORPER SUSCIPIT LOBORTIS NISL UT ALIQUIP EX EA COMMODO
            CONSEQUAT. DUIS AUTEM VEL EUM IRIURE DOLOR IN HENDRERIT IN VULPUTATE
            VELIT ESSE MOLESTIE CONSEQUAT, VEL ILLUM DOLORE EU FEUGIAT NULLA
            FACILISIS AT VERO EROS ET ACCUMSAN ET IUSTO ODIO DIGNISSIM QUI
            BLANDIT PRAESENT LUPTATUM ZZRIL DELENIT AUGUE DUIS DOLORE TE FEUGAIT
            NULLA FACILISI. LOREM IPSUM DOLOR SIT AMET, CONS ECTETUER ADIPISCING
            ELIT, SED DIAM NONUMMY NIBH EUISMOD TINCIDUNT UT LAOREET DOLORE
            MAGNA ALIQUAM ERAT VOLUTPAT. UT WISI ENIM AD MINIM VENIAM, QUIS
            NOSTRUD EXERCI TATION ULLAMCORPER SUSCIPIT LOBORTIS NISL UT ALIQUIP
            EX EA COMMODO CONSEQUAT. LOREM IPSUM DOLOR SIT AMET, CONSECTETUER
            ADIPISCING ELIT, SED DIAM NONUMMY NIBH EUISMOD TINCIDUNT UT LAOREET
            DOLORE MAGNA ALIQUAM ERAT VOLUTPAT. UT WISI ENIM AD MINIM VENIAM,
            QUIS NOSTRUD EXERCI TATION ULLAMCORPER SUSCIPIT LOBORTIS NISL UT
            ALIQUIP EX EA COMMODO CONSEQUAT. DUIS AUTEM VEL EUM IRIURE DOLOR IN
            HENDRERIT IN VULPUTATE VELIT ESSE MOLESTIE CONSEQUAT, VEL ILLUM
            DOLORE EU FEUGIAT NULLA FACILISIS AT VERO EROS ET ACCUMSAN ET IUSTO
            ODIO DIGNISSIM QUI BLANDIT PRAESENT LUPTATUM ZZRIL DELENIT AUGUE
            DUIS DOLORE TE FEUGAIT NULLA FACILISI. LOREM IPSUM DOLOR SIT AMET,
            CONS ECTETUER ADIPISCING ELIT, SED DIAM NONUMMY NIBH EUISMOD
            TINCIDUNT UT LAOREET DOLORE MAGNA ALIQUAM ERAT VOLUTPAT. UT WISI
            ENIM AD MINIM VENIAM, QUIS NOSTRUD EXERCI TATION ULLAMCORPER
            SUSCIPIT LOBORTIS NISL UT ALIQUIP EX EA COMMODO CONSEQUAT UT LAOREET
            DOLORE MAGNA ALIQUAM ERAT VOLUTPAT. UT WISI ENIM AD MINIM VENIAM,
            QUIS NOSTRUD EXERCI TATION ULLAMCORPER SUSCIPIT LOBORTIS NISL UT
            ALIQUIP EX EA COMMODO CONSEQUAT. DUIS AUTEM VEL EUM IRIURE DOLOR IN
            HENDRERIT IN VULPUTATE VELIT ESSE MOLESTIE CONSEQUAT, VEL ILLUM
            DOLORE EU FEUGIAT NULLA FACILISIS AT VERO EROS ET ACCUMSAN ET IUSTO
            ODIO DIGNISSIM QUI BLANDIT PRAESENT LUPTATUM ZZRIL DELENIT AUGUE
            DUIS DOLORE TE FEUGAIT NULLA FACILISI. LOREM IPSUM DOLOR SIT AMET,
            CONS ECTETUER ADIPISCING ELIT, SED DIAM NONUMMY NIBH EUISMOD
            TINCIDUNT UT LAOREET DOLORE MAGNA ALIQUAM ERAT VOLUTPAT. UT WISI
            ENIM AD MINIM VENIAM, QUIS NOSTRUD EXERCI TATION ULLAMCORPER
            SUSCIPIT LOBORTIS NISL UT ALIQUIP EX EA COMMODO CONSEQUAT UT LAOREET
            DOLORE MAGNA ALIQUAM ERAT VOLUTPAT. UT WISI ENIM AD MINIM VENIAM,
            QUIS NOSTRUD EXERCI TATION ULLAMCORPER SUSCIPIT LOBORTIS NISL UT
            ALIQUIP EX EA COMMODO CONSEQUAT. DUIS AUTEM VEL EUM IRIURE DOLOR IN
            HENDRERIT IN VULPUTATE VELIT ESSE MOLESTIE CONSEQUAT, VEL ILLUM
            DOLORE EU FEUGIAT NULLA FACILISIS AT VERO EROS ET ACCUMSAN ET IUSTO
            ODIO DIGNISSIM QUI BLANDIT PRAESENT LUPTATUM ZZRIL DELENIT AUGUE
            DUIS DOLORE TE FEUGAIT NULLA FACILISI. LOREM IPSUM DOLOR SIT AMET,
            CONS ECTETUER ADIPISCING ELIT, SED DIAM NONUMMY NIBH EUISMOD
            TINCIDUNT UT LAOREET DOLORE MAGNA ALIQUAM ERAT VOLUTPAT. UT WISI
            ENIM AD MINIM VENIAM, QUIS NOSTRUD EXERCI TATION ULLAMCORPER
            SUSCIPIT LOBORTIS NISL UT ALIQUIP EX EA COMMODO CONSEQUAT
          </Text>
        </View>
      </ScrollView>
    </PageContainer>
  );
};
export default PrivacyPolicy;

const styles = StyleSheet.create({
  paraBox: {
    paddingHorizontal: 30,
    marginVertical: 10,
  },
  paraText: {
    fontSize: 11,
    textAlign: 'left',
    lineHeight: 18,
  },
});
