export const assets = {
  splash: require('../../assets/splash.gif'),
  splashold: require('../../assets/splashold.gif'),
  bell: require('../../assets/icons/bell.png'),
  chevron: require('../../assets/icons/chevron.png'),
  back: require('../../assets/icons/back.png'),
  edit: require('../../assets/icons/edit.png'),
  hamburger: require('../../assets/icons/Hamburger_icon.png'),
  cart: require('../../assets/icons/cart.png'),
  list: require('../../assets/icons/list.png'),
  logo: require('../../assets/images/logo.png'),
  logoWhite: require('../../assets/images/logo-white.png'),
  vlogo: require('../../assets/vlogo.png'),
  vlogoDark: require('../../assets/vlogoDark.png'),
  mainLogo: require('../../assets/icon.png'),
  bg: require('../../assets/images/chbg.jpg'),
  loginBg: require('../../assets/images/loginbg.png'),
  forgetBg: require('../../assets/images/forgot_bg.jpeg'),
  clock: require('../../assets/icons/clock.png'),
  circle: require('../../assets/icons/circle.png'),
  calendar: require('../../assets/icons/calendar.png'),
  shake: require('../../assets/images/shake.png'),
  apple: require('../../assets/icons/apple.png'),
  lock: require('../../assets/icons/lock.png'),
  phone: require('../../assets/icons/phone-call.png'),
  instagram: require('../../assets/icons/instagram.png'),
  email: require('../../assets/icons/email.png'),
  whatsapp: require('../../assets/icons/whatsapp.png'),
  refresh: require('../../assets/icons/refresh.png'),
  google: require('../../assets/icons/google.png'),
  comingSoon: require('../../assets/images/comingsoon.gif'),
  visa: require('../../assets/images/visa.png'),
  naps: require('../../assets/images/naps.png'),
  visamaster: require('../../assets/images/visamaster.png'),
  wallet: require('../../assets/icons/wallet.png'),


};
